/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.3.1/userguide/building_java_projects.html
 */

plugins {
  java
  id("org.jetbrains.kotlin.jvm") version "1.6.10"
}

repositories {
  // Use Maven Central for resolving dependencies.
  mavenCentral()

  maven { url = uri("https://papermc.io/repo/repository/maven-public/") }

  // For MockBukkit
  maven { url = uri("https://jitpack.io") }
}

val bundled by configurations.creating {
  this.extendsFrom(configurations.implementation.get())
  this.isTransitive = false
}

dependencies {

  // Start using Kotlin
  val depKotlin = "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
  bundled(depKotlin) {
    this.isTransitive = true
  }

  // And its reflection Module
  implementation("org.jetbrains.kotlin:kotlin-reflect")

  // Use MockBukkit for testing.
  testImplementation("com.github.seeseemelk:MockBukkit-v1.15:0.3.1-SNAPSHOT")
  // Which,
  // Use JUnit Jupiter for testing.
  testImplementation("org.junit.jupiter:junit-jupiter:5.8.2")

  // // This dependency is used by the application.
  // implementation("com.google.guava:guava:30.1.1-jre")

  // compileOnly("io.papermc.paper:paper-api:1.17-R0.1-SNAPSHOT")
  // compileOnly("org.spigotmc:spigot-api:1.16.5-R0.1-SNAPSHOT")
  compileOnly("org.bukkit:bukkit:1.15.2-R0.1-SNAPSHOT")

  // Add generator for plugin.yml

  val depAnnotations = "org.spigotmc:plugin-annotations:1.2.3-SNAPSHOT"
  compileOnly(depAnnotations)
  annotationProcessor(depAnnotations)

  // also enable for testing
  testCompileOnly(depAnnotations)
  testAnnotationProcessor(depAnnotations)
}

tasks.test {
  // Use JUnit Platform for unit tests
  useJUnitPlatform()
}

java {
  this.sourceCompatibility = JavaVersion.VERSION_1_8
  this.targetCompatibility = JavaVersion.VERSION_1_8
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().configureEach {
  kotlinOptions {
    jvmTarget = "1.8"
  }
}

tasks.jar {
  from(bundled.asFileTree.files.map { zipTree(it) })

  duplicatesStrategy = org.gradle.api.file.DuplicatesStrategy.WARN

  // this.destinationDirectory.set(layout.buildDirectory)
}

base {
  this.libsDirectory.set(layout.buildDirectory)
  this.distsDirectory.set(layout.buildDirectory)
}