/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package xxx.ykis.eventhook;

import org.bukkit.plugin.java.JavaPlugin;

import java.io.File;
import java.io.IOException;

import org.bukkit.configuration.ConfigurationSection;
import org.bukkit.configuration.file.YamlConfiguration;

// For plugin.yml generation
import org.bukkit.plugin.java.annotation.plugin.*;
import org.bukkit.plugin.java.annotation.plugin.author.Author;
import org.bukkit.plugin.PluginLoadOrder;

// For MockBukkit
import org.bukkit.plugin.java.JavaPluginLoader;
import org.bukkit.plugin.PluginDescriptionFile;

/**
 * The entry point to the whole plugin,
 * the manager of the whole plugin lifecycle,
 * the interface to commands from the outside,
 * and the first-stage guard of the configuration schema.
 */
// Base Information for plugin.yml
@Plugin(name = "EventHook", version = "0.0-alpha")
@ApiVersion(ApiVersion.Target.v1_15)
@Author(value = "ykis-0-0")
@LogPrefix(value = "EventHook(Test)")
@LoadOrder(PluginLoadOrder.STARTUP)
public class PluginMain extends JavaPlugin {

  private AthleteRegistry registry;

  private boolean checkConfSchema() {
    YamlConfiguration configTemplate = YamlConfiguration.loadConfiguration(this.getTextResource("defaults.yml"));
    boolean permissible = true;
    boolean needSupplyDrop = false;

    int epochUsed = configTemplate.getInt("schema.epoch");
    if(epochUsed != this.getConfig().getInt("schema.epoch")){
      this.getLogger().warning("The existing config.yml is from another epoch, copying the new template.");
      permissible = false;
      needSupplyDrop = true;
    }

    int revisionUsed = configTemplate.getInt("schema.revision");
    if(revisionUsed != this.getConfig().getInt("schema.revision")){
      this.getLogger().warning("A newer revision of config.yml exists, copy a new template.");
      needSupplyDrop = true; // revision change isn't blocking
    }

    if(needSupplyDrop) {
      try {
        configTemplate.save(new File(this.getDataFolder(), "config.yml.newtemplate"));
        this.getLogger().info("New template saved as config.yml.newtemplate");
      } catch(IOException e) {
        e.printStackTrace();
        this.getLogger().severe("Could not save new configuration template");
      }
    }

    return permissible;
  }

  //#region Internal Lifecycle management
  private void announceCommencement() {
    if(!this.getConfig().isConfigurationSection("events")) {
      this.getLogger().severe("In config.yml[events]: Type mismatch, Map expected");
    }

    this.registry = new AthleteRegistry(this);

    ConfigurationSection applicationForms = this.getConfig().getConfigurationSection("events");

    int countAthletes = this.registry.processApplications(applicationForms);

    this.getLogger().info(String.format(
      "%d applications received, of which %d are approved",
      applicationForms.getKeys(false).size(), countAthletes
    ));

    this.registry.makeReady();

    this.getLogger().info("All runners on their position.");
  }

  void endOfEvent() {
    this.registry.dismissParticipants();
    this.registry = null;
  }
  //#endregion

  //#region External Lifecycle compliance
  @Override
  public void onEnable() {
    this.getLogger().info("Enabled!");

    // In case for first launch
    this.getDataFolder().mkdir();
    this.saveDefaultConfig();
    this.getConfig().options().copyDefaults(false);

    // If the config.yml schema isn't compatible
    if(!this.checkConfSchema()) {
      this.getLogger().warning("Disabling myself, see you next time~");
      this.setEnabled(false);
      return;
    }
  }

  @Override
  public void onDisable() {
    this.getLogger().info("Disabled!");
  }
  //#endregion

  //#region Constructors for MockBukkit
  public PluginMain() {
    super();
  }

  public PluginMain(JavaPluginLoader loader, PluginDescriptionFile description, File dataFolder, File file) {
    super(loader, description, dataFolder, file);
  }
  //#endregion
}
