schema: # Do NOT change this section unless you know what you are doing!
  epoch: 0
  revision: 0

events:
  load: # User-defined id for an entry
    event: org.bukkit.event.server.ServerLoadEvent # Fully Qualified Class Name of Event
    priority: MONITOR # org.bukkit.event.EventPriority.*
    wants:
      - Type # TODO
    run:
      executable: "who"
      args:
        - am
        - i

# Try new

runners:
  webhook:
    executable: "who"
    args:
      - am
      - i

events2:
  load:
    event: org.bukkit.event.server.ServerLoadEvent # Fully Qualified Class Name of Event
    priority: MONITOR # org.bukkit.event.EventPriority.*
    runners:
      - webhook